### ISSUE TITLE
启动盘无法启动

### ISSUE THREAD

**Issue by ongstan** [totemofwolf/Thinkpad-T460p-OSX-EFI#1]
制作顺序是transmac制作mojave启动盘，然后替换你的clover文件夹
出现的问题是，出现苹果标识后，变成一个禁止符号，然后就不动了
感谢你的工作和可能的帮助

**Comment by totemofwolf** [comment]
**我的系统是10.13，没折腾最新的**

> 安装时将ig-platform-id改为0x12345678（必须改，空着也不行！）进入安装，另外可能还需要设置

```
<key>Intel</key>
<true/>
```

参考：
[10.12和10.13的核显framebuffer五国问题解决方案汇总](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1696023)

**Comment by ongstan** [comment]
感谢，很顺利的安装成功了。顺利的解决了。
虽然有些部分的工作情况不如你的README，看来还要折腾（实在没有折腾过这个，拖你们的福才能用用上）。
