### ISSUE TITLE
T460P TrackPoint Button not work

### ISSUE THREAD

**Issue by ljj038** [totemofwolf/Thinkpad-T460p-OSX-EFI#11]
我和你的机器一样，也是美版。

现在除了三个实体的鼠标按钮不管用之外，其他还没有发现什么问题。

这三个实体按键有什么修复方案没有。我查了好多都没有解决

主要的不方便在于，当想拖动一个窗口的时候，由于这个触摸版只有下半部分是可以点击的，所以不太好拖动，想用实体按键加触摸版的方式来做。

有没有方案，麻烦方便的时候回复一下。

<img width="544" alt="Screen Shot 2019-09-19 at 8 35 37 PM" src="https://user-images.githubusercontent.com/5117313/65244461-2bfc4b80-db1d-11e9-9e72-ddc73c21f47a.png">

**Comment by ljj038** [comment]
补充一下

我是Mojave 10.14.6

<img width="544" alt="Screen Shot 2019-09-19 at 8 44 28 PM" src="https://user-images.githubusercontent.com/5117313/65244991-539fe380-db1e-11e9-8d83-6fdd9ef811db.png">

**Comment by totemofwolf** [comment]
Magic Trackpad 2/1 解君愁，23333（逃

**Comment by ljj038** [comment]
> Magic Trackpad 2/1 解君愁，23333（逃

好主意。。。

另外 今天给我推送Catalina了 升还是不升

**Comment by totemofwolf** [comment]
> > Magic Trackpad 2/1 解君愁，23333（逃
> 
> 好主意。。。
> 
> 另外 今天给我推送Catalina了 升还是不升

慌什么..

**Comment by ljj038** [comment]
![1570860781445](https://user-images.githubusercontent.com/5117313/66696015-8a6eb100-ecfa-11e9-8023-7acd16665e6a.jpg)


完全自动tax升级上来的，升级完之后重新运行了one key hidpi 搞定
一切和之前一样
