### ISSUE TITLE
T460P美版i5-6440HQ无限重启，无法进入安装。

### ISSUE THREAD

**Issue by raychl** [totemofwolf/Thinkpad-T460p-OSX-EFI#2]
你好我使用这个EFI，把 ig-platform-id修改为0x12345678，进不到安装界面。
我用https://blog.daliansky.net/macOS-High-Sierra-10.13.6-17G2112-Release-Special-with-Clover-4606-original-mirror.html 提供的镜像，以及内部提供的530显卡对应的config文件，修改 ig-platform-id修改为0x191d0000，可以安装mac，并进入系统，但是显卡显示为7m。
我应该如何驱动我的显卡，有什么需要注意的么，或者有没有什么相关的文章？
出现类似的情况，有一些文章说：Your graphics is not loading. You'll need to modify the DVMT pre-allocated memory in your BIOS settings to 96MB.
但是我没有在电脑的bios配置中找到该项，我应该如何配置？

**Comment by totemofwolf** [comment]
``` ig-platform-id ：0x191b0000 ```才是HD530..
我的EFI是6820HQ这个原生CPU，你可能需要改smbios （MBP 13,1）和DSDT吧？？
DVMT问题直接用 ```IntelGraphicsDVMTFixup.kext``` 应该就好了...

**Comment by raychl** [comment]
我的CPU是 I5-6440HQ，使用 0x191d0000 安装完毕后，可以进去系统，但是显卡的内存显示为7m，应该是显卡未能成功驱动。修改ig-platform-id ：0x191b0000 的话，会进不了系统，-v模式下看到卡死在第一屏，就是出现很多++号之前一行哪里。
我尝试处理一下DSDT，以及修改smbios，看看行不行。

**Comment by totemofwolf** [comment]
哦好的吧。。我看这里HD530 就是：191b https://www.intel.cn/content/www/cn/zh/products/processors/core/core-vpro/i5-6440hq.html

**Comment by raychl** [comment]
确实是191b。
根据这个教程（Intel FB-Patcher使用教程）
 https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html 
成功驱动了核显，按照教程一步搞定，还是挺简单的。
谢谢。

**Comment by totemofwolf** [comment]
.....

**Comment by cnyangyuan** [comment]
> 成功驱动了核显，按照教程一步搞定，还是挺简单的。

I5-6440HQ 这个要修改哪里啊？

**Comment by blackapplefan** [comment]
你好，我也是T460P 6820HQ的机器，因为刚接触黑苹果，不太熟悉，用这个EFI发现有很多报错，
ACPI Error: Method parse/execution failed [\.SB.PCI0.LPCB.EC.BAT0._STA] ....AE_NOT_EXIST
...
AppleBusPowerController: .... power supply unavailable....
然后直接就禁止标志了，先谢谢了

**Comment by blackapplefan** [comment]
另外用网上下载的带clover的镜像制作成U盘启动后，如何用你的EFI进行更新U盘上的EFI，DSDT和Kexts两个目录也要拷到U盘的EFI分区吗？还有版主的ACPI/origin下是否要清空？谢谢

**Comment by sirrusyqh** [comment]
Anonymous UUID:       556DAA7D-3966-8ACB-A550-128ED6FB4DD1

Fri Jun 12 22:25:35 2020

*** Panic Report ***
panic(cpu 0 caller 0xffffff8017d88c2d): Kernel trap at 0xffffff7f9a528c88, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000033, CR3: 0x000000001d6c1000, CR4: 0x00000000003627e0
RAX: 0x0000000000000000, RBX: 0xffffff8072537690, RCX: 0x0000000000000202, RDX: 0xffffff838f37b78b
RSP: 0xffffff83b0793a00, RBP: 0xffffff83b0793a30, RSI: 0xffffff83b0793ad0, RDI: 0xffffff8072537690
R8:  0xffffff83b0793870, R9:  0x0000000000000008, R10: 0x0000000000000010, R11: 0x0000000000000000
R12: 0xffffff8072537690, R13: 0xffffff7f9a598700, R14: 0x0000000000000000, R15: 0x0000000000004006
RFL: 0x0000000000010202, RIP: 0xffffff7f9a528c88, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000033, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff83b07934b0 : 0xffffff8017c6e166 
0xffffff83b0793500 : 0xffffff8017d96714 
0xffffff83b0793540 : 0xffffff8017d88a00 
0xffffff83b07935c0 : 0xffffff8017c20180 
0xffffff83b07935e0 : 0xffffff8017c6dbdc 
0xffffff83b0793710 : 0xffffff8017c6d99c 
0xffffff83b0793770 : 0xffffff8017d88c2d 
0xffffff83b07938f0 : 0xffffff8017c20180 
0xffffff83b0793910 : 0xffffff7f9a528c88 
0xffffff83b0793a30 : 0xffffff7f9a540308 
0xffffff83b0793a70 : 0xffffff7f9a540070 
0xffffff83b0793ac0 : 0xffffff7f9a53ffb7 
0xffffff83b0793b20 : 0xffffff7f9a53d765 
0xffffff83b0793b60 : 0xffffff7f9a54298c 
0xffffff83b0793b90 : 0xffffff7f9a547008 
0xffffff83b0793be0 : 0xffffff7f9a5680b4 
0xffffff83b0793c60 : 0xffffff7f9a569459 
0xffffff83b0793ca0 : 0xffffff7f9a56a142 
0xffffff83b0793cf0 : 0xffffff7f9a56160c 
0xffffff83b0793d30 : 0xffffff7f9a565d6d 
0xffffff83b0793d90 : 0xffffff7f9a51e267 
0xffffff83b0793e20 : 0xffffff7f989a5e99 
0xffffff83b0793e70 : 0xffffff7f989a534c 
0xffffff83b0793e90 : 0xffffff7f9a5be0a4 
0xffffff83b0793ed0 : 0xffffff8017ca77e4 
0xffffff83b0793f40 : 0xffffff8017ca7345 
0xffffff83b0793fa0 : 0xffffff8017c1f4f7 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f989a4000->0xffffff7f989acfff
         com.apple.driver.AppleACPIPlatform(6.1)[FC118BB9-2E67-35DD-BB25-BA6DFAF5AE88]@0xffffff7f9a518000->0xffffff7f9a5b3fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f989a4000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1850E7DA-E707-3027-A3AA-637C80B57219]@0xffffff7f98494000
            dependency: com.apple.driver.AppleSMC(3.1.9)[497D69E7-C1FB-3435-B4D9-ED1DC51727D1]@0xffffff7f989ad000
         com.apple.driver.AppleACPIEC(6.1)[00F1F962-B55B-3339-80D6-A0787A895E43]@0xffffff7f9a5bd000->0xffffff7f9a5c3fff
            dependency: com.apple.iokit.IOSMBusFamily(1.1)[9CFF73D8-2872-3FC0-AEE5-334587EAA4D0]@0xffffff7f9a473000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f989a4000
            dependency: com.apple.driver.AppleACPIPlatform(6.1)[FC118BB9-2E67-35DD-BB25-BA6DFAF5AE88]@0xffffff7f9a518000

BSD process name corresponding to current thread: kernel_task
Boot args: nv_disable=1 dart=0 enable-hdmi20 -v 

Mac OS version:
17E199

Kernel version:
Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64
Kernel UUID: 1B55340B-0B14-3026-8A47-1E139DB63DA3
Kernel slide:     0x0000000017a00000
Kernel text base: 0xffffff8017c00000
__HIB  text base: 0xffffff8017b00000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 2025439706714
last loaded kext at 34951689960: com.realtek.driver.RtWlanU1827	1827.4.b19 (addr 0xffffff7f99228000, size 4100096)
last unloaded kext at 459162044424: org.acidanthera.NVMeFix	1.0.0 (addr 0xffffff7f9b161000, size 20480)
loaded kexts:
(none)

EOF

System Profile:
Thunderbolt Bus: 
Boot Volume File System Type: apfs
PCI Card: Intel HD Graphics 530, VGA compatible controller, Internal@0,2,0
PCI Card: 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller, USB controller, Internal@0,20,0
PCI Card: 100 Series/C230 Series Chipset Family Thermal Subsystem, Signal processing controller, Internal@0,20,2
PCI Card: 100 Series/C230 Series Chipset Family MEI Controller #1, Communication controller, Internal@0,22,0
PCI Card: HM170/QM170 Chipset SATA Controller [AHCI Mode], SATA controller, Internal@0,23,0
PCI Card: 100 Series/C230 Series Chipset Family Power Management Controller, Memory controller, Internal@0,31,2
PCI Card: 100 Series/C230 Series Chipset Family HD Audio Controller, Audio device, Internal@0,31,3
PCI Card: 100 Series/C230 Series Chipset Family SMBus, SMBus, Internal@0,31,4
PCI Card: Intel I219LM2 PCI Express Gigabit Ethernet, Ethernet controller, Internal@0,31,6
PCI Card: RTS522A PCI Express Card Reader, Unassigned class, Internal@0,28,4/0,0
PCI Card: BCM4352 802.11ac Wireless Network Adapter, Network controller, Internal@0,28,0/0,0
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2133 MHz, Samsung, M471A2K43BB1-CPB
Memory Module: BANK 1/DIMM0, 16 GB, DDR4, 2134 MHz, Crucial Technology, CT16G4SFD8213.C16FAD
USB Device: USB 3.0 Bus
USB Device: Bluetooth HCI
USB Device: USB Receiver
Serial ATA Device: SAMSUNG MZ7LN512HMJP-000L7, 512.11 GB
Serial ATA Device: Lenovo SSD SL700 M.2 256G, 256.06 GB
Model: MacBookPro13,3, BootROM 254.0.0, 4 processors, Intel Core i7, 2.71 GHz, 32 GB, SMC 2.38f7
Graphics: Intel HD Graphics 530, Intel HD Graphics 530, Built-In
Network Service: Ethernet, Ethernet, en0
Bluetooth: Version 6.0.5f3, 3 services, 26 devices, 1 incoming serial ports
Model: MacBookPro13,3, BootROM 254.0.0, 4 processors, Intel Core i7, 2.71 GHz, 32 GB, SMC 2.38f7
Graphics: Intel HD Graphics 530, Intel HD Graphics 530, Built-In
Memory Module: BANK 0/DIMM0, 16 GB, DDR4, 2133 MHz, Samsung, M471A2K43BB1-CPB
Memory Module: BANK 1/DIMM0, 16 GB, DDR4, 2134 MHz, Crucial Technology, CT16G4SFD8213.C16FAD
Bluetooth: Version 6.0.5f3, 3 services, 26 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
PCI Card: Intel HD Graphics 530, VGA compatible controller, Internal@0,2,0
PCI Card: 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller, USB controller, Internal@0,20,0
PCI Card: 100 Series/C230 Series Chipset Family Thermal Subsystem, Signal processing controller, Internal@0,20,2
PCI Card: 100 Series/C230 Series Chipset Family MEI Controller #1, Communication controller, Internal@0,22,0
PCI Card: HM170/QM170 Chipset SATA Controller [AHCI Mode], SATA controller, Internal@0,23,0
PCI Card: 100 Series/C230 Series Chipset Family Power Management Controller, Memory controller, Internal@0,31,2
PCI Card: 100 Series/C230 Series Chipset Family HD Audio Controller, Audio device, Internal@0,31,3
PCI Card: 100 Series/C230 Series Chipset Family SMBus, SMBus, Internal@0,31,4
PCI Card: Intel I219LM2 PCI Express Gigabit Ethernet, Ethernet controller, Internal@0,31,6
PCI Card: RTS522A PCI Express Card Reader, Unassigned class, Internal@0,28,4/0,0
PCI Card: BCM4352 802.11ac Wireless Network Adapter, Network controller, Internal@0,28,0/0,0
Serial ATA Device: SAMSUNG MZ7LN512HMJP-000L7, 512.11 GB
Serial ATA Device: Lenovo SSD SL700 M.2 256G, 256.06 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth HCI
USB Device: USB Receiver
Thunderbolt Bus: 
请教下，有时电脑重启，是什么原因，小白一个，请指教
