### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by ongstan** [totemofwolf/Thinkpad-T460p-OSX-EFI#3]
很顺利的安装上了，但是会出现即刻性的kernel panic, 立即重启或者断电。
搜了一下hackintosh OACPIFAMILY之类的， 找到了一些immediately kernel panic相关的问题，但是都没有很好的给出原因。
主要的配置应该是和你的一样的，只有硬盘不一致， 以及我的屏幕是1k的。
因为没有太深入的玩过黑苹果， 所以想请教你一下， 这种问题大概是哪些部分出了问题？修改的话是什么样的思路。
感谢！

部分错误代码如下。
`Kernel Extensions in backtrace: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f8515b000->0xffffff7f85163fff com.apple.driver.AppleACPIPlatform(6.1)[B0282791-F78C-3A3D-A829-629AD847C7EA]@0xffffff7f86a13000->0xffffff7f86aaefff dependency: com.apple.iokit.IOACPIFamily(1.4)[95DA39BB-7C39-3742-A2E5-86C555E21D67]@0xffffff7f8515b000 dependency: com.apple.iokit.IOPCIFamily(2.9)[695C67B4-C637-3724-BFD5-F83CAE840AAA]@0xffffff7f84c94000 dependency: com.apple.driver.AppleSMC(3.1.9)[2D1E4A3F-A19E-3F12-878D-807CB79CD55F]@0xffffff7f85164000 com.apple.driver.AppleACPIEC(6.1)[4044E1DF-C416-3F42-B056-C07B8D2B305C]@0xffffff7f86ab8000->0xffffff7f86abefff dependencl`

**Comment by totemofwolf** [comment]
把 DSDT/patched 下的东西都拿走，重启（自己提取原始的，自行打补丁）；
还不行的话，尝试升级kexts/里面的东西到兼容 10.14的版本...

----

**Comment by ongstan** [comment]
感谢! 
没有找到问题的原因, 最后的解决方案是把你的和 fhaoquan的两个部分拼出来了一个自己能用的版本.
除了变频只有九档和休眠问题, 工作还算正常.
多问一句, 声卡驱动这一块你是怎么处理的? 是用applealc修改配置编译, 然后加 ssdt-hedf.dsdt来替换的吗?

**Comment by totemofwolf** [comment]
声卡直接使用Lilu+AppleALC+ properties就行了鸭。。
https://blog.daliansky.net/Intel-FB-Patcher-tutorial-and-insertion-pose.html
