### ISSUE TITLE
只有一个USB口可用

### ISSUE THREAD

**Issue by cn4** [totemofwolf/Thinkpad-T460p-OSX-EFI#5]
你好！安装好系统后，只有网口旁边的一个usb口可用，另外两个都不行，请问是什么原因呢？
我的电脑是T460P i5-6440H 集成显卡.

**Comment by totemofwolf** [comment]
恩，我也注意到了这个情况（USB 2.0设备会这样）。因为我的UsbPort.kext是在10.13.6早期版本上（未安装G3025安全更新的时候）使用fbPatcher做的定制，安装更新后这个方法貌似不好用了（无法和94352z蓝牙驱动很好共存）。你可以继续使用 USBInjectAll.kext 并打开kexttopatch 里面的端口限制
