### ISSUE TITLE
休眠问题

### ISSUE THREAD

**Issue by cn4** [totemofwolf/Thinkpad-T460p-OSX-EFI#6]
我这里有2个问题：
1. 合盖不能休眠；
2. 长时间不动自动休眠后，就无法再打开了，需要长按电源键关机后在重新开机，重新进入系统后，提示意外断电；

请问这种情况如果要修复，是单独要做什么操作吗？

**Comment by totemofwolf** [comment]
用SSDT-%PTSWAK-merge.aml + 基本改名（参考config.plist）就解决了鸭。
