### ISSUE TITLE
我也是T460P，但是CPU型号是I5-6440HQ 你能帮我改下config.plist吗

### ISSUE THREAD

**Issue by cnyangyuan** [totemofwolf/Thinkpad-T460p-OSX-EFI#7]
大哥你好，我也是我也是T460P
CPU：i5-6440hq
核显：hd530
独显：940mx
内存：4G+8G  DDR4 2133
你可以帮我改下EFI里面的config.plist吗？我在论坛找到你的帖子了，但是自己不会改，麻烦你，谢谢

**Comment by totemofwolf** [comment]
看这个：https://github.com/totemofwolf/Thinkpad-T460p-OSX-EFI/issues/2

**Comment by cnyangyuan** [comment]
我现在装的是这个：http://bbs.pcbeta.com/viewthread-1790952-1-1.html【目前我装了没问题，正常进系统】
装好之后将你的EFI文件替换进去对吗？
你发的这个链接我看了，核显，我知道修改ig-platform-id ：0x191b0000 CPU是修改哪里呢？
可以加我QQ吗7126311，谢谢。

**Comment by cnyangyuan** [comment]
> 看这个：#2

看完了，但是我还是没明白，i5-6440hq这个要修改哪里！

**Comment by totemofwolf** [comment]
orz...你修改CPU干啥。。

**Comment by cnyangyuan** [comment]
> orz...你修改CPU干啥。。

你的是i7啊，我的是i5，难道你的意思是 只要修改“ig-platform-id ：0x191b0000”这一个参数就行了嘛。

**Comment by totemofwolf** [comment]
你自己试嘛。。
