### ISSUE TITLE
制作的启动盘报错，帮忙看看，谢谢

### ISSUE THREAD

**Issue by blackapplefan** [totemofwolf/Thinkpad-T460p-OSX-EFI#8]
你好，我也是T460P 6820HQ的机器，因为刚接触黑苹果，不太熟悉，用这个EFI发现有很多报错，
ACPI Error: Method parse/execution failed [.SB.PCI0.LPCB.EC.BAT0._STA] ....AE_NOT_EXIST
...
AppleBusPowerController: .... power supply unavailable....
然后直接就禁止标志了，先谢谢了

另外用网上下载的带clover的镜像制作成U盘启动后，如何用你的EFI进行更新U盘上的EFI，DSDT和Kexts两个目录也要拷到U盘的EFI分区吗？还有版主的ACPI/origin下是否要清空？谢谢
![_20190116202555](https://user-images.githubusercontent.com/46746315/51249176-739a6880-19cd-11e9-96f5-a32f2e827263.jpg)

**Comment by totemofwolf** [comment]
电池|亮度|睡眠依赖DSDT和KEXT文件，，你不用我有啥办法？？
小红点就别折腾了直接买个apple 触摸板算逑。

**Comment by blackapplefan** [comment]
谢谢，根目录下dsdt下的txt如何使用？根下的kext是不是要放到SLE下面重建缓存？谢谢
@totemofwolf
