### ISSUE TITLE
请问你这个风扇速度正常吗？

### ISSUE THREAD

**Issue by fast01** [totemofwolf/Thinkpad-T460p-OSX-EFI#9]
请问你这个风扇速度正常吗？

**Comment by cnyangyuan** [comment]
我现在没用这个，我在用别的，你的电脑是T460P吗？

**Comment by fast01** [comment]
是的。 T460P  Intel Core i5-6440HQ  我的其他的特性ok了。 就是风扇一直转，比较心烦

**Comment by fast01** [comment]
是不是cpu 变频不对？还是其他的地方问题？ 求教

**Comment by cnyangyuan** [comment]
一模一样的配置！我的也是美版的，建议你下载这个http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1809109&highlight=  截止到10.14.4还是完美的！

**Comment by cnyangyuan** [comment]
你用我发给你的那个链接里面的EFI吧

**Comment by fast01** [comment]
> 一模一样的配置！我的也是美版的，建议你下载这个http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1809109&highlight= 截止到10.14.4还是完美的！

好的， 我当前系统是10.13.6， 这个efi 支持这个版本吗？  风扇可以静音吗？或者停转吗？

**Comment by cnyangyuan** [comment]
试试，记得备份呢！如果是频率问题，再找解决办法！

**Comment by fast01** [comment]
好的。 多谢，稍后我试试，回聊

**Comment by totemofwolf** [comment]
风扇转速正常。已升级10.14.6，目前睡眠障碍；）

**Comment by totemofwolf** [comment]
睡眠唤醒已经修复；）
